server:
  port: 9990

spring:
  application:
    name: mcsv-minijuego
  thymeleaf:
    cache: false
    enabled: true
    servlet:
      prefix: /templates/
      suffix: .html




eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}