server:
  port: 8099

spring:
  application:
    name: mcsv-reportes
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/notificaciones}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    enabled: true
    servlet:
      prefix: /templates/
      suffix: .html

  mail:
    host: smtp.gmail.com
    port: 587
    username: brayandelgadodiaz03@gmail.com
    password: muspunqeepftmfma
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}




