server:
  port: 9090

spring:
  application:
    name: microservice-login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://reportes.cr4bj8rv1tz1.us-east-1.rds.amazonaws.com:3306/securitydb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    enabled: true
    servlet:
      prefix: /templates/
      suffix: .html
    mode: HTML5
    dialect: org.thymeleaf.spring5.dialect.SpringStandardDialect



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



