server:
  port: 9090

spring:
  application:
    name: microservice-login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://mysql-8ebd880-alumnos-859e.l.aivencloud.com:28982/securitydb}

    #jdbc:reportes.cr4bj8rv1tz1.us-east-1.rds.amazonaws.com:3306/securitydb
   # url: ${DB_URL:jdbc:mysql://localhost:3306/securitydb}
   # username: ${DB_USERNAME:root}
   # password: ${DB_PASSWORD:root}


  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  #thymeleaf:
   # cache: false
   # enabled: true
   # servlet:
   #   prefix: /templates/
   #   suffix: .html
   # mode: HTML5
   # dialect: org.thymeleaf.spring5.dialect.SpringStandardDialect

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/ # Asegura que los templates estén en src/main/resources/templates/
    suffix: .html
    mode: HTML
    dialect: org.thymeleaf.spring6.dialect.SpringStandardDialect # Actualizado para Spring Boot 3/Spring 6
  

feign:
  client:
    mcsv-reportes:
      url: ${FOREIGN_CLIENT_URL:http://localhost:8099/reportes}


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}



